### PR TITLE
feat: extra headers during initialization

### PR DESCRIPTION
**Pull request by aderihoJD**
Unfortunately, this feature https://github.com/trinodb/trino-js-client/pull/568 not fully provide possibility to apply extra headers for each request to Trino. They apply only for the first one (query) and we lose them later, in next() method. If we'll add extraHeaders during client initialization, they will apply for each request.
p.s. pretty urgent, if possible

### CODE REVIEW

**Comment by aderihoJD** [comment]
i agree CLA

ср, 25 сент. 2024 г. в 00:06, cla-bot[bot] ***@***.***>:

**Comment by nineinchnick** [comment]
This looks like a duplicate of #666

**Comment by nineinchnick** [comment]
@cla-bot check

**Comment by nineinchnick** [comment]
There's an open discussion in https://github.com/trinodb/trino/pull/15826 about allowing clients to send any HTTP headers. It would be better to discuss specific use cases.

Similar changes were suggested in both [the Trino Go client](https://github.com/trinodb/trino-go-client/pull/91), and [the Python client](https://github.com/trinodb/trino-python-client/pull/265), and both were rejected, because no sufficient use case was provided.

**Comment by aderihoJD** [comment]
@regadas could u review it?

**Comment by nineinchnick** [comment]
Please describe your use case, per my previous comment.

**Comment by aderihoJD** [comment]
> Please describe your use case, per my previous comment.

yes, sure. i left a description already. and in our case - we need an extra header to allow us communicate with trino inside cluster. that's why we need a **X-Forwarded-Proto: https** header for **each** request to trino.

**Comment by aderihoJD** [comment]
> Can you add a test that would verify this?

not sure

**Comment by aderihoJD** [comment]
@nineinchnick do we need smth from my side?

**Comment by nineinchnick** [comment]
Yes, this needs any kind of tests. A unit test would suffice, but we only have integration tests here. @regadas PTAL

**Comment by regadas** [comment]
@aderihoJD @nineinchnick sorry for dropping the ball a bit on this; Added a test to ensure propagation.

**Review by regadas — APPROVED** [review]

**Comment by mosabua** [comment]
Please note our commit guidelines when sending PRs @aderihoJD .. and also when merging @regadas 

See https://trino.io/development/process#pull-request-and-commit-guidelines-

and https://trino.io/development/process#pull-request-review-and--merge

**Comment by aderihoJD** [comment]
@regadas could we make a release with this changes?

**Comment by regadas** [comment]
@aderihoJD Sorry for the delay; https://github.com/trinodb/trino-js-client/releases/tag/v0.2.4

**Pull request merged**
